#!/bin/bash

# --- Compile list of files ---
# TODO: Get Base.
# -- Check "shell" in config. Default to bash.
#
# TODO: Get Addons.
# --- Import Addons ---
python ./scripts/addons_importer.py;

# --- Build RCs ---
# TODO: Write files to bin/ directory
# python ./scripts/build_rcs.py;

# --- Create Aliases ---
# TODO: Create aliases for new RC file.
# TODO: Backup existing and move old/existing RCs.